// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzesqThPwhHvOZHmWHcRBCCRExK_tTARg',
    appId: '1:17383665187:web:793d2e7ea638c519c98b96',
    messagingSenderId: '17383665187',
    projectId: 'tinytotscare-7f8e9',
    authDomain: 'tinytotscare-7f8e9.firebaseapp.com',
    databaseURL: 'https://tinytotscare-7f8e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinytotscare-7f8e9.appspot.com',
    measurementId: 'G-Q3YLZ2B888',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxf0yk-ULVKLkJn6oJxF_Ppk4K6LQdfbo',
    appId: '1:17383665187:android:36223ac23e4d1b2dc98b96',
    messagingSenderId: '17383665187',
    projectId: 'tinytotscare-7f8e9',
    databaseURL: 'https://tinytotscare-7f8e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinytotscare-7f8e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcgHgjS_uAfrHHnLGPDePKjNjVAO8XhU',
    appId: '1:17383665187:ios:4ba3f6346f001025c98b96',
    messagingSenderId: '17383665187',
    projectId: 'tinytotscare-7f8e9',
    databaseURL: 'https://tinytotscare-7f8e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinytotscare-7f8e9.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcgHgjS_uAfrHHnLGPDePKjNjVAO8XhU',
    appId: '1:17383665187:ios:4ba3f6346f001025c98b96',
    messagingSenderId: '17383665187',
    projectId: 'tinytotscare-7f8e9',
    databaseURL: 'https://tinytotscare-7f8e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinytotscare-7f8e9.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzesqThPwhHvOZHmWHcRBCCRExK_tTARg',
    appId: '1:17383665187:web:7f7380f445c0bc11c98b96',
    messagingSenderId: '17383665187',
    projectId: 'tinytotscare-7f8e9',
    authDomain: 'tinytotscare-7f8e9.firebaseapp.com',
    databaseURL: 'https://tinytotscare-7f8e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tinytotscare-7f8e9.appspot.com',
    measurementId: 'G-J6J82X7097',
  );
}
